version: "3.9"

services:
  postgres:
    image: postgres:17-alpine
    container_name: vieclam24h_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server/public/uploads:/app/public/uploads
    container_name: vieclam24h_server
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 8080
      HOST_DB: postgres
      PORT_DB: 5432
      USERNAME_DB: ${DB_USER}
      PASSWORD_DB: ${DB_PASSWORD}
      DATABASE_DB: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
    container_name: vieclam24h_client
    restart: unless-stopped
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  pgdata:
